GCTProject/GCTProject/Models/ViewModels/Details.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GCTProject.Models.ViewModels
{
    public class Details
    {

        //[Required]
        //[StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
        //[DataType(DataType.Password)]
        //[Display(Name = "Password")]
        //public string Password { get; set; }

        //[DataType(DataType.Password)]
        //[Display(Name = "Confirm password")]
        //[Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        //public string ConfirmPassword { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Phone]
        [Display(Name = "Phone number")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Email Confirmed")]
        public bool IsEmailConfirmed { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Full name")]
        public string FullName { get; set; }
    }
}

GCTProject/GCTProject/Controllers/PerformancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GCTProject;
using GCTProject.Data;
using GCTProject.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.ComponentModel;
using System.Reflection;

namespace GCTProject.Controllers
{
    [Authorize(Roles = "Manager,Admin,SalesStaff")]
    public class PerformancesController : Controller
    {
        private readonly GCTProjectContext _context;

        public PerformancesController(GCTProjectContext context)
        {
            _context = context;
        }

        // GET: Performances
        public async Task<IActionResult> Index()
        {
            return View(await _context.Performance.ToListAsync());
        }

        // GET: Performances/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance
                .FirstOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        //GET multipel files upload, not in use
        [HttpPost("UploadFiles")]
        public async Task<IActionResult> Post(List<IFormFile> files)
        {
            long size = files.Sum(f => f.Length);

            // full path to file in temp location
            var filePath = Path.GetTempFileName();

            foreach (var formFile in files)
            {
                if (formFile.Length > 0)
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            // process uploaded files
            // Don't rely on or trust the FileName property without validation.

            return Ok(new { count = files.Count, size, filePath });
        }


        //Get Photo for performance
        public ActionResult RenderPhoto(string photoId)
        {
            byte[] photo = (new GCTProjectContext()).Performance.Find(photoId).Picture;
            return File(photo, "image/jpeg");
        }



        // GET: Performances/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Performances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PriceBand,LiveDate,Name,Description,AgeRestriction,Picture")] PerformanceCreation performanceCreation, IFormFile file)
        {
            Performance performance = new Performance();

            var filePath = Path.GetTempFileName();

            if (file.Length > 0)
            {
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
            }
            
            if (ModelState.IsValid)
            {
                performance.Id = Guid.NewGuid().ToString();
                performance.PriceBand = performanceCreation.PriceBand;
                performance.LiveDate = performanceCreation.LiveDate;
                performance.Name = performanceCreation.Name;
                performance.Description = performanceCreation.Description;
                performance.AgeRestriction = performanceCreation.AgeRestriction.ToString();

                using (var memoryStream = new MemoryStream())
                {
                    await file.CopyToAsync(memoryStream);
                    performance.Picture = memoryStream.ToArray();

                    _context.Add(performance);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(performance);
        }

        //Post Upload, no longer used
        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile file)
        {
            // full path to file in temp location
            var filePath = Path.GetTempFileName();

            if (file.Length > 0)
            {
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
            }

            // process uploaded files
            // Don't rely on or trust the FileName property without validation.

            return Ok();
        }

        // GET: Performances/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance.FindAsync(id);
            if (performance == null)
            {
                return NotFound();
            }
            return View(performance);
        }

        // POST: Performances/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,PriceBand,LiveDate,Name,Description,AgeRestriction,Picture")] Performance performance)
        {
            if (id != performance.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(performance);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerformanceExists(performance.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(performance);
        }

        // GET: Performances/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performance = await _context.Performance
                .FirstOrDefaultAsync(m => m.Id == id);
            if (performance == null)
            {
                return NotFound();
            }

            return View(performance);
        }

        // POST: Performances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var performance = await _context.Performance.FindAsync(id);
            _context.Performance.Remove(performance);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Checks if performance exists
        private bool PerformanceExists(string id)
        {
            return _context.Performance.Any(e => e.Id == id);
        }
    }
}

GCTProject/GCTProject/Views/Performances/Create.cshtml
@model PerformanceCreation
@using GCTProject.Models

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Performance</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        
        <form method="post" enctype="multipart/form-data" asp-controller="Performances" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PriceBand" class="control-label"></label>
                <input asp-for="PriceBand" class="form-control" />
                <span asp-validation-for="PriceBand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LiveDate" class="control-label"></label>
                <input asp-for="LiveDate" class="form-control" />
                <span asp-validation-for="LiveDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgeRestriction" class="control-label"></label>
                <select asp-for="AgeRestriction" asp-items="Html.GetEnumSelectList<AgeGroup>()" class="form-control"></select>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload a picture</p>
                    <input asp-for="Picture" type="file" name="file" />
                </div>
            </div>
            @*
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Upload" asp-action="UploadFile"/>
            </div>
        </div>
            *@

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GCTProject/GCTProject/Views/Performances/Delete.cshtml
@model Performance

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Performance</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceBand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceBand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LiveDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LiveDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgeRestriction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgeRestriction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GCTProject/GCTProject/Views/Performances/Details.cshtml
@model Performance

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Performance</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PriceBand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PriceBand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LiveDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LiveDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgeRestriction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgeRestriction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GCTProject/GCTProject/Views/Performances/Edit.cshtml
@model Performance

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Performance</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PriceBand" class="control-label"></label>
                <input asp-for="PriceBand" class="form-control" />
                <span asp-validation-for="PriceBand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LiveDate" class="control-label"></label>
                <input asp-for="LiveDate" class="form-control" />
                <span asp-validation-for="LiveDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgeRestriction" class="control-label"></label>
                <input asp-for="AgeRestriction" class="form-control" />
                <span asp-validation-for="AgeRestriction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GCTProject/GCTProject/Views/Performances/Index.cshtml
@model IEnumerable<Performance>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PriceBand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LiveDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AgeRestriction)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PriceBand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LiveDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgeRestriction)
            </td>
            <td>
                <img src="@Url.Action("RenderPhoto", "Performances", new { photoId = item.Id })" width="100" height="100" alt="Performance Image" />
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>