GCTProject/GCTProject/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GCTProject.Data;
using GCTProject.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Stripe;

namespace GCTProject.Controllers
{
    public class BookingController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _contextId;
        private readonly GCTProjectContext _contextData;

        public BookingController(
                    UserManager<IdentityUser> userManager,
                    ApplicationDbContext contextId,
                    GCTProjectContext context)
        {
            _userManager = userManager;
            _contextId = contextId;
            _contextData = context;
        }

        //GET Basket/Booking
        public async Task<IActionResult> Basket()
        {
            var user = await _userManager.GetUserAsync(User);
            var basketTickets = from bt in _contextData.BasketTickets
                                select bt;
            basketTickets = basketTickets.Where(bt => bt.UserId == user.Id);

            if (basketTickets != null)
            {

                var savedRepresentations = new List<TicketsInBasket>();
                
                foreach (var item in basketTickets)
                {
                    var tb = new TicketsInBasket();
                    tb.Id = item.UserId;
                    tb.Cost = Int32.Parse(item.Performance.PriceBand.Split('-')[0]);
                    tb.RowNumber = item.Seat.RowName;
                    tb.SeatNumber = item.Seat.ColumnNumber;
                    tb.PerformanceName = item.Performance.Name;
                    tb.PerformanceTime = item.Performance.LiveDate;
                    savedRepresentations.Add(tb);
                }

                return View(savedRepresentations);
            }

            return View();
        }

        //GET Buy/Booking
        public async Task<IActionResult> Buy(string Id = null)
        {
            if(Id == null)
            {
                return NotFound();
            }

            var performance = await _contextData.Performance.FindAsync(Id);
            var seatsBooked =  _contextData.BookedSeats.Where(s => s.PerformanceId == performance.Id);
            IQueryable<string> rows = from m in _contextData.Seats
                                      orderby m.RowName
                                      select m.RowName;
            IQueryable<string> column = from m in _contextData.Seats
                                      orderby m.ColumnNumber
                                      select m.ColumnNumber;
            List<string> columns1, rows1;
             rows1 = new List<string>();
            columns1 = new List<string>();
            for (int j=0; j<24; j++)
            {
                columns1.Add("Select");
                rows1.Add("Select");
            }
            string[] splitPrices = performance.PriceBand.Split("-");
            decimal startPrice = decimal.Parse(splitPrices[0]);
            decimal endPrice = decimal.Parse(splitPrices[1]);
            List<decimal> costs = new List<decimal>();
            int rowsNumber = rows.Distinct().Count();
            costs.Add(decimal.Parse(endPrice.ToString("0.00")));
            for (int i = 2; i < rowsNumber; i++)
            {
                costs.Add(decimal.Parse((endPrice - (endPrice - startPrice)/(i)).ToString("0.00")));
            }
            costs.Add(decimal.Parse(startPrice.ToString("0.00")));

            BuyTicket buyTicket = new BuyTicket() { PerformanceId = performance.Id, PerformanceName = performance.Name, rowNames = rows.Distinct().ToList(), Costs = costs, LiveDate = performance.LiveDate,
                BookedSeats = seatsBooked.ToList(), Seats = _contextData.Seats.ToList(),
                rowTags = new SelectList(rows.Distinct().ToList()), columnsTags = new SelectList(column.Distinct().ToList()),
                chosenColumns =columns1, chosenRows = rows1
        };
            ViewData["rows"] = rowsNumber;
            ViewData["columns"] = column.Distinct().Count();
            
            return View(buyTicket);
        }

        //GET Charge/Booking
        public IActionResult Charge(string stripeEmail, string stripeToken)
        {
            var customers = new CustomerService();
            var charges = new ChargeService();

            var customer = customers.Create(new CustomerCreateOptions
            {
                Email = stripeEmail,
                SourceToken = stripeToken
            });

            var charge = charges.Create(new ChargeCreateOptions
            {
                Amount = 500,
                Description = "Initial Charge",
                Currency = "gbp",
                CustomerId = customer.Id
            });

            return View();
        }
    }
}

GCTProject/GCTProject/Views/Booking/Basket.cshtml
@model IEnumerable<TicketsInBasket>

@{
    ViewData["Title"] = "Basket";
}

<h1>Basket</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PerformanceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PerformanceTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RowNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SeatNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PerformanceName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PerformanceTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RowNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SeatNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    <a asp-action="DeleteTicket" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<button asp-action="ChargeBasket" type="submit" class="btn btn-default">Checkout</button>

GCTProject/GCTProject/Views/Booking/Buy.cshtml
@model BuyTicket


@{
    ViewData["Title"] = "Buy";
    int rows = (int)ViewData["Rows"];
    int columns = (int)ViewData["Columns"];
    int count = 0;
    int count1 = 0;
}

<h1>Buy Ticket</h1>
<hr />


<form method="post" asp-controller="Booking" asp-action="Buy">
    <div class="row">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Chosen Performance: </label>
                @Html.DisplayFor(model => model.PerformanceName)
            </div>
            <div class="form-group">
                <label class="control-label">Performance Date and Time: </label>
                @Html.DisplayFor(model => model.LiveDate)
            </div>
            <div class="form-group">
                <label>Select how many seats you wish to book:</label>
                @Html.DropDownListFor(m => m.ManySeats, Enumerable.Range(1, 24).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), new { id = "numberOfSeats", onclick = "javascript:setSeats();" })
            </div>
        </div>
    </div>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-8">
                @Html.DropDownListFor(m => m.chosenRows[count], @Model.rowTags, "Select Row", new { @class = "pos0" })
                @Html.DropDownListFor(m => m.chosenColumns[count], @Model.columnsTags, "Select Seat", new { @class = "pos0" })
            </div>

        </div>
        @for (int i = 0; i < Model.chosenRows.Count() / 8; i++)
        {
        <div class="row">
            @for (int k = 0; k < Model.chosenRows.Count(); k++)
            {
                count1++;
                <div class="col-8">
                    @Html.DropDownListFor(m => m.chosenRows[count], @Model.rowTags, "Select Row", new { @class = "pos" + count1, style = "display:none;" })
                    @Html.DropDownListFor(m => m.chosenColumns[count], @Model.columnsTags, "Select Seat", new { @class = "pos" + count1, style = "display:none;" })
                </div>
            }

        </div>
        }
    </div>

        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-8 text-center" style="border:2px solid black;">
                    Stage
                </div>
            </div>
        </div>
        <br />
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-md-8 text-center">
                    Seating Plan
                </div>
            </div>
            <br />
            @for (int i = 1; i <= rows; i++)
            {
                <div class="row">
                    <div class="col-4 col-sm text-center mb4" style="padding:10px;">Prices Row @Html.DisplayFor(model => model.rowNames[i - 1]): @Html.DisplayFor(model => model.Costs[i - 1]) &#163;
                    </div>
                    </div>
                    <div class="row">

                        @for (int j = 1; j <= columns; j++)
                        {
                            <div class="col-10 col-sm" style="padding:2px;">
                                <span style="background-color:@(Model.BookedSeats.ElementAt(count).Booked == true ? "red" : "white"); height:20px; width:20px; padding:4px; border:2px solid black;">
                                    @Html.DisplayFor(model => model.Seats.ElementAt(count).RowName)
                                    @Html.DisplayFor(model => model.Seats.ElementAt(count).ColumnNumber)

                                </span>
                            </div>
                            count++;
                        }
                    </div>
                    <br />
                    }

                    <div class="form-group">
                        <input type="submit" value="Buy Now" class="btn btn-primary" />
                    </div>
                </div>
</form>
<div>
    <a asp-action="Index" asp-controller="Home">Back to List</a>
</div>

<script>
    var seats = 0;
    function setSeats() {
        var count1 = $('#numberOfSeats').val();
       
            for (var i = 23; i > 0; i--) {
                $(".pos" + i).hide();
            }

        for (var i = 1; i < count1; i++)
        {   
            $(".pos" + i).show(500);
        }
    }

    //var changeColor = function (obj) {

    //    if (obj.value < 6) {
    //        obj.style.backgroundColor = 'green';
    //    } else if (obj.value >= 6 && obj.value <= 9) {
    //        obj.style.backgroundColor = 'orange';
    //    } else if (obj.value > 9) {
    //        obj.style.backgroundColor = 'red';
    //    }

    //};
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GCTProject/GCTProject/Views/Booking/Charge.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>You successfully paid <strong>$5.00</strong></h2>